#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_routes:
    resource: '../src/Controller/'
    type: annotation
    prefix: '/api'

api_login_check:
    path: /api/login